title: CyberTraining at UNCW, 2023 and 2024
description: "Cybertraining for junior marine science researchers at the beautiful coastal city of Wilmington, North Carolina."
logos:
  - image: /assets/images/nsf-logo.png
    alt: National Science Foundation
    link: https://www.nsf.gov
  - image: /assets/images/uncw-logo.png
    alt: University of North Carolina Wilmington
    link: https://uncw.edu

timezone: "America/New_York"

navigation:
  Home: "/"
  Call for Participants: "/cfp"
  Schedule: "/schedule"
  Organizers: "/organizers"


markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
