title: CyberTraining at UNCW, 2023 and 2024
description: “Cybertraining for junior marine science researchers at the beautiful coastal city of Wilmington, North Carolina.”
markdown: kramdown
theme: minima
